// <auto-generated />
using System;
using GamifiedLearningPlatform.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamifiedLearningPlatform.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251125173752_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GamifiedLearningPlatform.DAL.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("XpAward")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Assignments__3214EC07A1B2C3D4");

                    b.HasIndex("StudentId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("GamifiedLearningPlatform.DAL.Entities.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("XpRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id")
                        .HasName("PK__Badges__3214EC0789A1B2C3");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ__Badges__Name");

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("GamifiedLearningPlatform.DAL.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("TotalXp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id")
                        .HasName("PK__Students__3214EC075A4B3A2E");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ__Students__Email");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("GamifiedLearningPlatform.DAL.Entities.StudentBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EarnedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__StudentBadges__3214EC07D4E5F2C7");

                    b.HasIndex("BadgeId");

                    b.HasIndex("StudentId", "BadgeId")
                        .IsUnique()
                        .HasDatabaseName("UQ__StudentBadges__StudentId_BadgeId");

                    b.ToTable("StudentBadges");
                });

            modelBuilder.Entity("GamifiedLearningPlatform.DAL.Entities.Assignment", b =>
                {
                    b.HasOne("GamifiedLearningPlatform.DAL.Entities.Student", "Student")
                        .WithMany("Assignments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Assignments_Students");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GamifiedLearningPlatform.DAL.Entities.StudentBadge", b =>
                {
                    b.HasOne("GamifiedLearningPlatform.DAL.Entities.Badge", "Badge")
                        .WithMany("StudentBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_StudentBadges_Badges");

                    b.HasOne("GamifiedLearningPlatform.DAL.Entities.Student", "Student")
                        .WithMany("StudentBadges")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_StudentBadges_Students");

                    b.Navigation("Badge");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GamifiedLearningPlatform.DAL.Entities.Badge", b =>
                {
                    b.Navigation("StudentBadges");
                });

            modelBuilder.Entity("GamifiedLearningPlatform.DAL.Entities.Student", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("StudentBadges");
                });
#pragma warning restore 612, 618
        }
    }
}
